comment: false
coverage:
  status:
    project:
      default: false
      cli:
        paths:
          - 'crates/jxl-oxide-cli/'
        informational: true
      lib:
        paths:
          - '!crates/jxl-oxide-cli/'
        informational: true
    patch:
      default:
        informational: true
    changes:
      default:
        informational: true
github_checks:
  annotations: false
