on:
  push:
    branches:
      - main
      - v*.x
  workflow_dispatch: {}
name: Build

jobs:
  build:
    name: Compile
    strategy:
      matrix:
        os:
          - ubuntu-24.04
          - windows-2022
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        id: toolchain
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-dot-cargo-${{ steps.toolchain.outputs.cacheKey }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-dot-cargo-${{ steps.toolchain.outputs.cacheKey }}-
            ${{ runner.os }}-dot-cargo-
      - name: Detect host triple
        id: detect-host
        shell: bash
        run: |
          rustc -vV | sed -ne 's/^host: /host=/p' >> "$GITHUB_OUTPUT"
      - run: cargo build --release
      - uses: actions/upload-artifact@v4
        with:
          name: jxl-oxide-cli-${{ steps.detect-host.outputs.host }}
          path: |
            target/release/jxl-oxide
            target/release/jxl-oxide.exe
  cross:
    name: Cross-compile
    strategy:
      matrix:
        os:
          - ubuntu-24.04
          - ubuntu-24.04-arm
        target:
          - x86_64-unknown-linux-gnu
          - armv7-unknown-linux-gnueabihf
          - aarch64-unknown-linux-gnu
        exclude:
          - os: ubuntu-24.04
            target: armv7-unknown-linux-gnueabihf
          - os: ubuntu-24.04
            target: aarch64-unknown-linux-gnu
          - os: ubuntu-24.04-arm
            target: x86_64-unknown-linux-gnu
    runs-on: ${{ matrix.os }}
    steps:
      - if: matrix.target == 'armv7-unknown-linux-gnueabihf'
        name: Install cross build tools
        run: 'sudo apt update && sudo apt upgrade -y crossbuild-essential-armhf'
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        id: toolchain
        with:
          targets: ${{ matrix.target }}
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-dot-cargo-${{ steps.toolchain.outputs.cacheKey }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-dot-cargo-${{ steps.toolchain.outputs.cacheKey }}-
            ${{ runner.os }}-dot-cargo-
      - run: cargo build --release --target ${{ matrix.target }}
        env:
          CARGO_TARGET_ARMV7_UNKNOWN_LINUX_GNUEABIHF_LINKER: 'arm-linux-gnueabihf-gcc'
      - uses: actions/upload-artifact@v4
        with:
          name: jxl-oxide-cli-${{ matrix.target }}
          path: |
            target/${{ matrix.target }}/release/jxl-oxide

  wasm:
    name: WebAssembly
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        id: toolchain
        with:
          targets: wasm32-unknown-unknown
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-dot-cargo-${{ steps.toolchain.outputs.cacheKey }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-dot-cargo-${{ steps.toolchain.outputs.cacheKey }}-
            ${{ runner.os }}-dot-cargo-
      - name: Install wasm-pack
        uses: taiki-e/install-action@v2
        with:
          tool: wasm-pack@0.13.0
      - name: Install wasm-bindgen
        uses: taiki-e/install-action@v2
        with:
          tool: wasm-bindgen@0.2.93
      - name: Build WebAssembly module
        working-directory: crates/jxl-oxide-wasm
        run: |
          RUSTFLAGS='-C target-feature=+simd128' wasm-pack build --release --target web --reference-types
          node ./update-package-json.mjs
          wasm-pack pack
      - uses: actions/upload-artifact@v4
        with:
          name: jxl-oxide-wasm
          path: crates/jxl-oxide-wasm/pkg/jxl-oxide-wasm-*.tgz
          compression-level: 0
